id: 51f54000fdea40a0b9fcbf1e66b0eedc
initial_creation_type: ocr
source_metadata:
  volumes:
    84b01d5210b94c6cb9e7bdcc4e833d2f:
      base_file: v105.txt
      image_group_id: I1PD95951
      title: རྩོད་པའི་རིགས་པའི་འགྲེལ་པ་དོན་རྣམ་པར་འབྱེད་པ།
      total_pages: 1054
      volume_number: 106
